const photos=[...document.querySelectorAll('.photo img')].map(img=>({src:img.src,alt:img.alt}));
photos.push(
  {src:'https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=1200&q=85',alt:'Bedroom with queen bed, crisp linens, and bedside lighting'},
  {src:'https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=1200&q=85',alt:'Bright, fully equipped kitchen with cooking essentials'},
  {src:'https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?auto=format&fit=crop&w=1200&q=85',alt:'Kitchen dining counter and preparation area'}
);
const modal=document.getElementById('galleryModal'), galleryBody=document.getElementById('galleryBody'), lightbox=document.getElementById('lightbox');
let activeIndex=0,previousFocus=null,guests=1,toastTimer;
const API='/api', listingId='mirashya-ug10';
let nightlyRate=8200,cleaningCost=900,serviceCost=1250,currency='INR',selectedCheckIn='',selectedCheckOut='',calendarMonth=(()=>{const today=new Date();return new Date(today.getFullYear(),today.getMonth(),1)})(), selectingDate='checkIn',calendarUnavailable=new Set(),calendarRenderVersion=0;
const money=value=>new Intl.NumberFormat('en-IN',{style:'currency',currency,maximumFractionDigits:0}).format(value);
const localDateKey=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const toast=(message)=>{const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2400)};
function openGallery(index=0){previousFocus=document.activeElement;activeIndex=index;galleryBody.innerHTML='';photos.forEach((photo,i)=>{const img=document.createElement('img');img.src=photo.src.replace(/w=\d+/,'w=1400');img.alt=photo.alt;img.loading=i>1?'lazy':'eager';img.addEventListener('click',()=>openLightbox(i));galleryBody.append(img)});modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';document.querySelector('.gallery-count').textContent=`${photos.length} photos`;document.getElementById('galleryClose').focus()}
function closeGallery(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow='';previousFocus?.focus()}
function renderLightbox(){const p=photos[activeIndex];document.getElementById('lightboxImage').src=p.src.replace(/w=\d+/,'w=1800');document.getElementById('lightboxImage').alt=p.alt;document.querySelector('.lightbox-count').textContent=`${activeIndex+1} / ${photos.length}`}
function openLightbox(index){activeIndex=index;renderLightbox();lightbox.classList.add('open');lightbox.setAttribute('aria-hidden','false');document.querySelector('.lightbox-close').focus()}
function closeLightbox(){lightbox.classList.remove('open');lightbox.setAttribute('aria-hidden','true');if(modal.classList.contains('open'))galleryBody.children[activeIndex]?.focus()}
function stepPhoto(delta){activeIndex=(activeIndex+delta+photos.length)%photos.length;renderLightbox()}
document.querySelectorAll('.photo').forEach(el=>el.addEventListener('click',()=>openGallery(Number(el.dataset.photo))));
document.getElementById('galleryClose').addEventListener('click',closeGallery);
document.querySelector('.lightbox-close').addEventListener('click',closeLightbox);
document.querySelector('.lightbox-prev').addEventListener('click',()=>stepPhoto(-1));document.querySelector('.lightbox-next').addEventListener('click',()=>stepPhoto(1));
document.addEventListener('keydown',e=>{if(lightbox.classList.contains('open')){if(e.key==='ArrowRight')stepPhoto(1);if(e.key==='ArrowLeft')stepPhoto(-1);if(e.key==='Escape')closeLightbox()}else if(modal.classList.contains('open')&&e.key==='Escape')closeGallery()});
document.getElementById('saveBtn').addEventListener('click',e=>{const btn=e.currentTarget, saved=btn.getAttribute('aria-pressed')!=='true';btn.setAttribute('aria-pressed',String(saved));btn.querySelector('.heart').textContent=saved?'♥':'♡';btn.querySelector('.heart').style.color=saved?'#ff385c':'';btn.querySelector('.save-label').textContent=saved?'Saved':'Save';toast(saved?'Added to your wishlist':'Removed from your wishlist')});
document.getElementById('modalSave').addEventListener('click',()=>document.getElementById('saveBtn').click());
document.getElementById('shareBtn').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);toast('Link copied to clipboard')}catch{toast('Share this stay with someone you love')}});
document.getElementById('guestToggle').addEventListener('click',()=>{const menu=document.getElementById('guestMenu');menu.hidden=!menu.hidden});
document.querySelector('.minus').addEventListener('click',()=>{guests=Math.max(1,guests-1);document.getElementById('guestCount').textContent=guests;document.querySelector('#guestToggle span').innerHTML=`${guests} guest${guests===1?'':'s'} <b>⌄</b>`});
document.querySelector('.plus').addEventListener('click',()=>{guests=Math.min(4,guests+1);document.getElementById('guestCount').textContent=guests;document.querySelector('#guestToggle span').innerHTML=`${guests} guests <b>⌄</b>`});
function paintCalendar(){const today=localDateKey(new Date()),grids=[...document.querySelectorAll('.calendar-grid')];grids.forEach((grid,monthOffset)=>{const month=new Date(calendarMonth.getFullYear(),calendarMonth.getMonth()+monthOffset,1),monthName=month.toLocaleDateString('en-US',{month:'long',year:'numeric'});grid.innerHTML='';grid.setAttribute('aria-label',`${monthName} dates`);['Su','Mo','Tu','We','Th','Fr','Sa'].forEach(day=>{const label=document.createElement('span');label.textContent=day;label.setAttribute('aria-hidden','true');grid.append(label)});const offset=month.getDay(),days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();for(let i=0;i<offset;i++){const blank=document.createElement('span');blank.setAttribute('aria-hidden','true');grid.append(blank)}for(let day=1;day<=days;day++){const date=new Date(month.getFullYear(),month.getMonth(),day),key=localDateKey(date),unavailable=calendarUnavailable.has(key),isSelected=key===selectedCheckIn||key===selectedCheckOut,btn=document.createElement('button');btn.type='button';btn.textContent=day;btn.dataset.date=key;btn.setAttribute('aria-label',`${date.toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})}${unavailable?' — booked night':''}`);btn.setAttribute('aria-pressed',String(isSelected));btn.classList.toggle('unavailable',unavailable);btn.disabled=key<today||(unavailable&&selectingDate==='checkIn');if(isSelected)btn.classList.add('selected');else if(selectedCheckIn&&selectedCheckOut&&key>selectedCheckIn&&key<selectedCheckOut)btn.classList.add('in-range');btn.addEventListener('click',()=>selectDate(key));grid.append(btn)}});const titles=document.querySelectorAll('.calendar-month-titles strong');titles[0].textContent=calendarMonth.toLocaleDateString('en-US',{month:'long',year:'numeric'});titles[1].textContent=new Date(calendarMonth.getFullYear(),calendarMonth.getMonth()+1,1).toLocaleDateString('en-US',{month:'long',year:'numeric'})}
async function renderCalendar(){const version=++calendarRenderVersion;paintCalendar();const months=[calendarMonth,new Date(calendarMonth.getFullYear(),calendarMonth.getMonth()+1,1)],monthKeys=months.map(month=>`${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,'0')}`);try{const responses=await Promise.all(monthKeys.map(month=>fetch(`${API}/listings/${listingId}/availability?month=${month}`)));if(responses.some(response=>!response.ok))return;const data=await Promise.all(responses.map(response=>response.json()));if(version!==calendarRenderVersion)return;calendarUnavailable=new Set(data.flatMap(item=>item.unavailable));paintCalendar()}catch{}}
function syncBookingFields(){document.querySelector('#checkinField span').textContent=selectedCheckIn||'Add date';document.querySelector('#checkoutField span').textContent=selectedCheckOut||'Add date';const heading=document.getElementById('calendarHeading'),hint=document.getElementById('calendarHint');if(selectedCheckIn&&!selectedCheckOut){heading.textContent='Choose your check-out date';hint.textContent=`Check-in: ${new Date(`${selectedCheckIn}T00:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric'})}. Now choose a check-out date.`}else if(selectedCheckIn&&selectedCheckOut){heading.textContent='Your selected dates';hint.textContent=`${new Date(`${selectedCheckIn}T00:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric'})} – ${new Date(`${selectedCheckOut}T00:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric'})}. Choose another date to start a new range.`}else{heading.textContent='Select check-in date';hint.textContent='Choose your check-in and check-out dates.'}if(selectedCheckIn&&selectedCheckOut){const nights=(Date.parse(`${selectedCheckOut}T00:00:00Z`)-Date.parse(`${selectedCheckIn}T00:00:00Z`))/86400000,subtotal=nightlyRate*nights;document.getElementById('nightLine').textContent=`${money(nightlyRate)} x ${nights} night${nights===1?'':'s'}`;document.getElementById('nightSubtotal').textContent=money(subtotal);document.getElementById('totalPrice').textContent=money(subtotal+cleaningCost+serviceCost)}else{document.getElementById('nightLine').textContent=`${money(nightlyRate)} x 5 nights`;document.getElementById('nightSubtotal').textContent=money(nightlyRate*5);document.getElementById('totalPrice').textContent=money(nightlyRate*5+cleaningCost+serviceCost)}}
async function selectDate(key){if(selectingDate==='checkIn'||!selectedCheckIn||key<=selectedCheckIn){selectedCheckIn=key;selectedCheckOut='';selectingDate='checkOut';toast('Now choose your check-out date')}else{selectedCheckOut=key;try{const result=await fetch(`${API}/listings/${listingId}/availability?from=${selectedCheckIn}&to=${selectedCheckOut}`),availability=await result.json();if(!result.ok||!availability.available){selectedCheckOut='';selectingDate='checkOut';toast(availability.error||'Those dates are not available. Choose another check-out date.')}else{selectingDate='checkIn';toast('Dates are available')}}catch{selectedCheckOut='';selectingDate='checkOut';toast('Could not check availability. Please try another date.')}}renderCalendar();syncBookingFields()}
async function loadListing(){try{const response=await fetch(`${API}/listings/${listingId}`);if(!response.ok)throw new Error('Listing could not be loaded');const data=await response.json();nightlyRate=data.nightlyRate;cleaningCost=data.cleaningFee;serviceCost=data.serviceFee;currency=data.currency;document.getElementById('nightlyRate').textContent=money(nightlyRate);document.getElementById('cleaningFee').textContent=money(cleaningCost);document.getElementById('serviceFee').textContent=money(serviceCost);syncBookingFields()}catch{toast('Backend unavailable. Start the app with npm start.')}}
document.getElementById('checkinField').addEventListener('click',()=>{selectingDate='checkIn';document.querySelector('.calendar').scrollIntoView({behavior:'smooth',block:'center'});toast('Choose a check-in date')});
document.getElementById('checkoutField').addEventListener('click',()=>{selectingDate=selectedCheckIn?'checkOut':'checkIn';document.querySelector('.calendar').scrollIntoView({behavior:'smooth',block:'center'});toast(selectedCheckIn?'Choose a check-out date first':'Choose a check-in date first')});
document.getElementById('reserveBtn').addEventListener('click',async()=>{if(!selectedCheckIn||!selectedCheckOut){toast('Choose check-in and check-out dates');document.querySelector('.calendar').scrollIntoView({behavior:'smooth',block:'center'});return}const button=document.getElementById('reserveBtn');button.disabled=true;button.textContent='Checking availability…';try{const response=await fetch(`${API}/bookings`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({listingId,checkIn:selectedCheckIn,checkOut:selectedCheckOut,guests})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Reservation could not be created');toast(`Reservation saved · ${result.id.slice(0,8)} · ${money(result.totalBeforeTaxes)} before taxes`)}catch(error){toast(error.message)}finally{button.disabled=false;button.textContent='Reserve'}});
document.getElementById('showMore').addEventListener('click',e=>{const p=e.currentTarget.previousElementSibling;if(e.currentTarget.dataset.open){p.textContent='Unwind in this romantic one-bedroom serviced apartment at Mirashya UG10 in Candolim. Thoughtful comforts, a private jacuzzi, and an easy base for a Goa getaway.';e.currentTarget.dataset.open='';e.currentTarget.innerHTML='Show more <span>→</span>'}else{p.textContent+=' Enjoy a fully equipped kitchen, a relaxed living area, and a comfortable bedroom after a day exploring Candolim and the North Goa coast.';e.currentTarget.dataset.open='true';e.currentTarget.textContent='Show less'}});
document.querySelectorAll('.month-row button').forEach((btn,index)=>btn.addEventListener('click',()=>{calendarMonth=new Date(calendarMonth.getFullYear(),calendarMonth.getMonth()+(index===0?-1:1),1);renderCalendar()}));
document.querySelector('.clear-dates').addEventListener('click',()=>{selectedCheckIn='';selectedCheckOut='';selectingDate='checkIn';renderCalendar();syncBookingFields()});
renderCalendar();syncBookingFields();loadListing();
